services:
  eunomia-app:
    container_name: eunomia-app
    image: "ghcr.io/ls1intum/eunomia-app:latest"
    restart: unless-stopped
    volumes:
      - ./knowledge:/app/knowledge
    # Map port 8082 if you want external access
    ports:
      - "8082:8082"
    environment:
      - EMAIL_ADDRESS
      - EMAIL_PASSWORD
      - IMAP_SERVER
      - SMTP_SERVER
      - IMAP_PORT
      - SMTP_PORT
      - USE_OPENAI
      - USE_AZURE
      - GPU_USER
      - GPU_PASSWORD
      - GPU_HOST
      - GPU_MODEL
      - GPU_URL
      - ANGELOS_URL
      - OPENAI_MODEL
      - ANGELOS_APP_API_KEY
    networks:
      - angelos-network

networks:
  angelos-network:
    external: true