services:
  chatbot:
    image: "ghcr.io/ls1intum/angelos-ui:latest"
    container_name: chatbot
    expose:
      - "80" 
    networks:
      - angelos-network 

  chatbot-org5:
    image: "ghcr.io/ls1intum/angelos-ui:org5-latest"
    container_name: chatbot-org5
    expose:
      - "80"
    networks:
      - angelos-network

networks:
  angelos-network:
    external: true