services:
  eunomnia-app:
    container_name: eunomnia-app
    image: "ghcr.io/ls1intum/eunomnia-app:latest"
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - angelos-network


networks:
  angelos-network:
    external: true
