services:
  eunomnia-app:
    container_name: eunomnia-app
    image: "ghcr.io/ls1intum/eunomnia-app:latest"
    restart: unless-stopped
    volumes:
      - ./knowledge:/app/knowledge
    environment:
      - EMAIL_ADDRESS
      - EMAIL_PASSWORD
      - IMAP_SERVER
      - SMTP_SERVER
      - IMAP_PORT
      - SMTP_PORT
      - USE_OPENAI
      - USE_AZURE
      - GPU_USER
      - GPU_PASSWORD
      - GPU_HOST
      - GPU_MODEL
      - GPU_URL
      - ANGELOS_URI
      - ANGELOS_PORT
      - OPENAI_MODEL
      - STUDY_PROGRAMS_FOLDER
      - ANGELOS_APP_API_KEY
    networks:
      - angelos-network


networks:
  angelos-network:
    external: true
