services:
  angelos-ui:
    image: "ghcr.io/ls1intum/angelos-ui:latest"
    container_name: angelos-ui
    ports:
      - "443:443"
    expose:
      - "443"
    networks:
      - angelos-network

networks:
  angelos-network:
    external: true
