services:
  angelos-ui:
    image: "ghcr.io/ls1intum/angelos-ui:latest"
    container_name: angelos-ui
    ports:
      - "443:443"
    expose:
      - "443"
    volumes:
      - /var/lib/rbg-cert/2024-10-31T11:10:43+01:00:/etc/ssl/certs:ro
    networks:
      - angelos-network

networks:
  angelos-network:
    external: true
