services:
  angelos-app:
    container_name: angelos-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./knowledge:/app/knowledge
    env_file:
      - development.env
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    networks:
      - angelos-network

networks:
  angelos-network:
    name: angelos-network
    driver: bridge
    external: true
