version: "3.8"

services:
  db:
    image: postgres:13
    container_name: angelos-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.postgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    networks:
      - angelos-network

  angelos-server:
    image: ghcr.io/ls1intum/angelosai/angelos-server:latest
    container_name: angelos-server
    depends_on:
      - db
    ports:
      - "9007:9007"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - uploads_volume:/app/uploads
    networks:
      - angelos-network

volumes:
  postgres_db_data:
  postgres_backups:
  uploads_volume:

networks:
  angelos-network:
    external: true