services:
  chatbot:
    image: "ghcr.io/ls1intum/angelosai/angelos-ui:latest"
    container_name: chatbot
    expose:
      - "80" 
    networks:
      - angelos-network 

  chatbot-org3:
    image: "ghcr.io/ls1intum/angelosai/angelos-ui-org3-latest"
    container_name: chatbot-heilbronn
    expose:
      - "80"
    networks:
      - angelos-network

networks:
  angelos-network:
    external: true