name: Deploy Eunomia

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ vars.ENABLE_DEPLOYMENT == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Eunomia Image
        uses: docker/build-push-action@v6
        with:
          platforms: amd64, arm64
          file: mail-system/Dockerfile
          context: mail-system
          tags: ghcr.io/ls1intum/angelosai/eunomia-app:latest
          push: true

  deploy:
    if: ${{ vars.ENABLE_DEPLOYMENT == 'true' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Mail System Compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          source: "mail-system/docker-compose.yml"
          target: "/home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/"

      - name: SSH to VM and Create .env.prod for Eunomia
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
            rm /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod || true
            touch /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "IMAP_SERVER=${{ vars.IMAP_SERVER }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "SMTP_SERVER=${{ vars.SMTP_SERVER }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "IMAP_PORT=${{ vars.IMAP_PORT }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "SMTP_PORT=${{ vars.SMTP_PORT }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "USE_OPENAI=${{ vars.USE_OPENAI }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "USE_AZURE=${{ vars.USE_AZURE }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "GPU_USER=${{ secrets.GPU_USER }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "GPU_PASSWORD=${{ secrets.GPU_PASSWORD }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "GPU_HOST=${{ vars.GPU_HOST }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "GPU_MODEL=${{ vars.GPU_MODEL }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "GPU_URL=${{ vars.GPU_URL }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "OPENAI_MODEL=${{ vars.OPENAI_MODEL }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod
            echo "ANGELOS_APP_API_KEY=${{ secrets.EUNOMIA_SECRET }}" >> /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod

      - name: SSH to VM and Execute Docker-Compose Up for Eunomia
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
            if ! docker network inspect angelos-network >/dev/null 2>&1; then
              echo "Network 'angelos-network' does not exist, creating it..."
              docker network create angelos-network
            fi
            docker network ls
            docker compose -f /home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/docker-compose.yml --env-file=/home/${{ vars.VM_USERNAME }}/${{ github.repository }}/mail-system/.env.prod up --pull=always -d --force-recreate --remove-orphans